apiVersion: v1
kind: ConfigMap
metadata:
  name: trafficgenerator-configmap
  labels:
    app: trafficgenerator
data:
  trafficgenerator-config.yaml: |+
    {{- toYaml $.Values.trafficgenerator.config | nindent 12 }}