{
 "title": "TidalScale Master Thesis Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Masters Thesis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Running Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs",
     "legendFormat": "Number of Running Jobs"
    }
   ]
  },
  {
   "title": "Flink JobManager CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_CPU_Load",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Flink TaskManager Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used / flink_taskmanager_Status_JVM_Memory_Heap_Committed",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Flink JobManger Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used / flink_jobmanager_Status_JVM_Memory_Heap_Committed",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Flink TaskManager CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of Registered TaskManagers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers",
     "legendFormat": "Number of TaskManagers"
    }
   ]
  },
  {
   "title": "Kafka lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_lag_max) / count(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_lag_max)"
    }
   ]
  },
  {
   "title": "Kafka Messages in Per Second by Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_server_brokertopicmetrics_messagesinpersec_count[2m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Flink Ingestion Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate)"
    }
   ]
  },
  {
   "title": "Throughput by Operator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operator_name) (rate(flink_taskmanager_job_task_operator_numRecordsOut[2m]))",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Kafka Bytes In Per Second by Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_server_brokertopicmetrics_bytesinpersec_count[2m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "95th Percentile Latency by Operator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (operator_id) (flink_taskmanager_job_latency_source_id_operator_id_operator_subtask_index_latency{quantile=\"0.95\"})",
     "legendFormat": "{{operator_id}}"
    }
   ]
  },
  {
   "title": "Flink Task Number of Records In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job_name) (rate(flink_taskmanager_job_task_numRecordsIn[2m]))",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Average Latency by Quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (quantile) (flink_taskmanager_job_latency_source_id_operator_id_operator_subtask_index_latency)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "End-to-End Latency 95th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (operator_id) (flink_taskmanager_job_latency_source_id_operator_id_operator_subtask_index_latency{quantile=\"0.95\", operator_id=\"ea632d67b7d595e5b851708ae9ad79d6\"})",
     "legendFormat": "{{operator_id}}"
    }
   ]
  },
  {
   "title": "Task Backpressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (task_name) (flink_taskmanager_job_task_isBackPressured)",
     "legendFormat": "{{task_name}}"
    }
   ]
  }
 ]
}