apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    prometheus.io/port: "9999"
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-08-01T17:35:26Z"
  generation: 1
  labels:
    app: flink-cluster
    component: jobmanager
    type: flink-native-kubernetes
  name: flink-cluster
  namespace: default
  resourceVersion: "121052"
  uid: 6bb246b8-89a4-4c58-baac-f78103b38ba3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: flink-cluster
      component: jobmanager
      type: flink-native-kubernetes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9999"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: flink-cluster
        component: jobmanager
        type: flink-native-kubernetes
    spec:
      containers:
      - args:
        - bash
        - -c
        - kubernetes-jobmanager.sh kubernetes-application
        command:
        - /docker-entrypoint.sh
        env:
        - name: _POD_IP_ADDRESS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: eu.gcr.io/msc-thesis-354309/quickstart:latest
        imagePullPolicy: IfNotPresent
        name: flink-main-container
        ports:
        - containerPort: 8081
          name: rest
          protocol: TCP
        - containerPort: 6123
          name: jobmanager-rpc
          protocol: TCP
        - containerPort: 6124
          name: blobserver
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1600Mi
          requests:
            cpu: "1"
            memory: 1600Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/flink/conf
          name: flink-config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: flink-service-account
      serviceAccountName: flink-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: logback-console.xml
            path: logback-console.xml
          - key: log4j-console.properties
            path: log4j-console.properties
          - key: flink-conf.yaml
            path: flink-conf.yaml
          name: flink-config-flink-cluster
        name: flink-config-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-08-01T17:35:28Z"
    lastUpdateTime: "2022-08-01T17:35:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-08-01T17:35:26Z"
    lastUpdateTime: "2022-08-01T17:35:28Z"
    message: ReplicaSet "flink-cluster-64d857494d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
