apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-trace-generator-deployment
  labels:
    app: real-trace-generator
spec:
  replicas: 5
  selector:
    matchLabels:
      app: real-trace-generator
  template:
    metadata:
      labels:
        app: real-trace-generator
    spec:
      containers:
      - name: real-trace-generator
        image: eu.gcr.io/msc-thesis-354309/real-trace-generator
        ports:
        - containerPort: 80