#########################################
## Global variables for All TidalScale components
global:
  projectId: thesistidalscale
  # Message Broker to Use: [kafka, pubsub, kafka_local]
  broker: kafka
  kafka:
    # Bootstrap Server Location, Kafka: <ip:port>
    broker_ip: kafka.default.svc.cluster.local
    port: 9092
    # Topics
    metric_topic: metrics
    metric_topic_partitions: 1
    data_topic: data
    data_topic_partitions: 8
    agg_prediction_topic: agg_prediction
    agg_prediction_topic_partitions: 1
  pubsub:
    # Topic to produce traffic to
    topic_id: data
    # Batch publishing, true/false
    batch: true
  kafka_local:
    # Bootstrap Server Location, Kafka: <ip:port>
    broker_ip: localhost
    port: 9092
  prometheus:
    query_path: /api/v1/query
    url: prometheus-rest.default.svc.cluster.local:9090
  logger:
    log_to_file: false
    log_path: /tmp/app.log
  postgres:
      host: tidalscale-postgresql.default.svc.cluster.local
      password: admin
      table: configurations
      database: tidalscale
      user: postgres

#######################################
## Global variables for the Flink Reactive subchart
flink-reactive:
  enabled: true

#######################################
## Global variables for the Autoscaling Controller chart
autoscalingcontroller:
  enabled: true
  ## Configuration for Autoscaling Controller Meter
  config:
    k8s:
      flink-taskmanager: flink-taskmanager
      namespace: default
      flink-reactive-path: k8s/
    config:
      rescale_window: 180
      metric_frequency: 2
      parallelization_upper_bound: 10
      parallelization_lower_bound: 1
    thresholds:
      cpu_max: 0.8
      cpu_min: 0.4
      mem_max: 0.9
    deployment: gcp

#######################################
## Global variables for the Metrics Reporter chart
metricsreporter:
  enabled: true
  ## Configuration for Metrics Reporter
  config:
    config:
      metric_frequency: 2

############################################
## Global variables for the Performance Meter chart
performancemeter:
  ## boolean to enable/disable chart
  enabled: true
  ## Configuration for Performance Meter
  config:
    thresholds:
      cpu_max: 0.8
      cpu_min: 0.2
      mem_max: 0.9
      rescale_cooldown: 30 # Seconds
    config:
      rescale_window: 120
      metric_frequency: 2  

############################################
## Global variables for the Performance Meter Postgresql Instance
postgresql:
  enabled: true

#########################################
## Global variables for the Prediction Aggregator chart
predictionaggregator:
  ## boolean to enable/disable chart
  enabled: true
  ## Configuration for Prediction Aggregator
  config:
    rescale_window: 180  # Seconds
    metric_frequency: 2  # Seconds
    lt_prediction_frequency: 60 # 300 for normal trace
    forecast_horizon: 3 # number of predictions in the future
    traces_per_hour: 12
    trace_history_duration_hours: 20 # 3 days / 5
    time_interval: 60 # 300 for normal trace
    MSE_bounds: 8
    spike_window: 10
    base_regression_length: 10

#########################################
## Global variables for the Traffic Generator chart
trafficgenerator:
  ## boolean to enable/disable chart
  enabled: true
